# Generated by Django 2.0.2 on 2018-04-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_suspend',
            name='e_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_suspend',
            name='s_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_terminate',
            name='e_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stock_terminate',
            name='s_date',
            field=models.CharField(max_length=10),
        ),
    ]
