# Generated by Django 2.1 on 2018-06-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='authors',
            field=models.CharField(default='xxu', max_length=20),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
