# Generated by Django 2.1 on 2018-02-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogfiles',
            name='files_list',
        ),
        migrations.DeleteModel(
            name='BlogFiles',
        ),
    ]
