# Generated by Django 2.1 on 2018-06-15 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='money',
            options={'ordering': ['date']},
        ),
    ]
