# Generated by Django 2.1 on 2018-06-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0002_auto_20180615_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
