# Generated by Django 2.1 on 2018-06-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0003_auto_20180615_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
