# Generated by Django 2.1 on 2018-06-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0004_auto_20180615_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
