# Generated by Django 2.1 on 2018-06-20 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost', '0005_auto_20180620_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='name',
            field=models.TextField(max_length=1024),
        ),
    ]
