# Generated by Django 2.1 on 2018-03-07 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('uploadfile', models.FileField(upload_to='ebooks/%Y/%m/%d/', verbose_name='文件')),
                ('accessnums', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='图书名称')),
                ('authors', models.CharField(max_length=100, verbose_name='作者列表')),
                ('detial', models.TextField(verbose_name='内容简介')),
                ('accessnums', models.IntegerField(default=0)),
                ('thumbupnums', models.IntegerField(default=0, verbose_name='点赞')),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updateuser', models.CharField(default='defaultuser', max_length=30, verbose_name='uploaduser')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='分类名称')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='出版社名称')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='books',
            name='booktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.BookType'),
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.Publisher'),
        ),
        migrations.AddField(
            model_name='bookfiles',
            name='book_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebook.Books'),
        ),
    ]
