# Generated by Django 2.0 on 2018-01-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='uploadfile',
            field=models.FileField(blank=True, upload_to='', verbose_name='文件'),
        ),
    ]
