# Generated by Django 2.1 on 2018-05-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='booktypes',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
