# Generated by Django 2.1 on 2018-05-11 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_books_booktypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='booktype',
        ),
    ]
