# Generated by Django 2.1 on 2018-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_remove_books_booktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfiles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(default='xxu', max_length=100, verbose_name='作者列表'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=256, verbose_name='图书名称'),
        ),
    ]
