# Generated by Django 2.0 on 2018-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_auto_20180117_0705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='booktype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='出版社名称'),
        ),
    ]
