# Generated by Django 2.0 on 2018-01-21 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0005_auto_20180118_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='authors',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.CharField(default='xuxiao', max_length=100, verbose_name='作者列表'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
