# Generated by Django 2.0 on 2018-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_auto_20180121_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfiles',
            name='accessnums',
            field=models.IntegerField(default=0, verbose_name='访问次数'),
        ),
        migrations.AlterField(
            model_name='bookfiles',
            name='thumbupnums',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
    ]
