# Generated by Django 2.0 on 2018-01-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0007_auto_20180121_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfiles',
            name='uploadfile',
            field=models.FileField(upload_to='ebooks/%Y/%m/%d/', verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='bookfiles',
            name='uploaduser',
            field=models.CharField(max_length=30, verbose_name='uploaduser'),
        ),
    ]
