# Generated by Django 2.2 on 2018-08-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Qts_Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qts_types', models.CharField(max_length=16)),
                ('name', models.TextField()),
                ('choosableanswer', models.TextField()),
                ('trainnums', models.IntegerField(default=0)),
                ('examnums', models.IntegerField(default=0)),
                ('correctnums', models.IntegerField(default=0)),
                ('errornums', models.IntegerField(default=0)),
                ('qts_setter', models.CharField(default='none', max_length=20)),
                ('qts_source', models.CharField(default='none', max_length=40)),
                ('qts_level', models.IntegerField(default=0)),
                ('qts_date', models.DateTimeField(auto_now_add=True)),
                ('qts_memo', models.TextField(default='None')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qts_Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qts_Testpapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testpaperserial', models.CharField(max_length=12)),
                ('testpaperdate', models.DateTimeField(auto_now_add=True)),
                ('testpaperdetail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Qts_Userid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='自动生成用户', max_length=20)),
                ('id_date', models.DateTimeField(auto_now_add=True)),
                ('id_ip', models.GenericIPAddressField()),
                ('id_password', models.CharField(default='111111', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='qts_testpapers',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainexam.Qts_Userid'),
        ),
        migrations.AddField(
            model_name='qts_library',
            name='qts_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainexam.Qts_Profession'),
        ),
    ]
