# Generated by Django 2.2 on 2018-08-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qts_userid',
            name='is_login',
            field=models.BooleanField(default=False),
        ),
    ]
