# Generated by Django 2.0.2 on 2018-04-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='名称')),
                ('uploadfile', models.FileField(upload_to='software/%Y/%m/%d/', verbose_name='文件')),
                ('accessnums', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Softs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('detial', models.TextField(verbose_name='内容简介')),
                ('accessnums', models.IntegerField(default=0)),
                ('updatetime', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updateuser', models.CharField(default='defaultuser', max_length=30, verbose_name='uploaduser')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoftType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='softs',
            name='softtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.SoftType'),
        ),
        migrations.AddField(
            model_name='softfiles',
            name='soft_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='software.Softs'),
        ),
    ]
