# Generated by Django 2.1 on 2018-05-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softs',
            name='softtypes',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
