# Generated by Django 2.1 on 2018-05-14 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0002_softs_softtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='softs',
            name='softtype',
        ),
    ]
