# Generated by Django 2.1 on 2018-06-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('software', '0003_remove_softs_softtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softfiles',
            name='name',
            field=models.CharField(max_length=256, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='softs',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
